#include "arduino_secrets.h"

/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/22db3eb7-f237-4d11-bc41-bcf77d0210b9

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int gas_Data;
  int light_Data;
  int noise_Data;
  int temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

int temperature_sensor = 15;
int light_sensor = 34;
int gas_sensor = 35;
int noise_sensor = 2;

const float BETA = 3975; // Beta value for the thermistor

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  pinMode(gas_sensor, INPUT);
  pinMode(light_sensor, INPUT);
  pinMode(noise_sensor, INPUT);
  pinMode(temperature_sensor, INPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  onGasDataChange();

  onTemperatureChange();

  onNoiseDataChange();

  onLightDataChange();


}


/*
  Since GasData is READ_WRITE variable, onGasDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGasDataChange()  {
  // Read Gas sensor value
  int gas_Data = analogRead(gas_sensor);

  Serial.print("Ligh Analog Value = ");
  Serial.print(gas_Data);   // the raw analog reading

  /*// Determine light level based on analog value
    if (gas_Data < 400) {
    Serial.println(" => Fault");
    } else {
    Serial.println(" => Normal");
    }*/

  delay(500);
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Read temperature sensor value
  int temperature = analogRead(temperature_sensor);
  float resistance = (float)(1023 - temperature) * 10000 / temperature; // Calculate resistance
  float celsius = 1 / ((log(resistance / 10000) / BETA) + (1 / 298.15)) - 273.15; // Calculate temperature in Celsius

  Serial.print("Temperature: ");
  Serial.print(celsius);
  Serial.println(" Â°C");

  // Control LED based on temperature
  if (celsius >= 21) {
    digitalWrite(14, HIGH); // Turn on LED
  } else {
    digitalWrite(14, LOW); // Turn off LED
  }

  delay(1000);

}

/*
  Since NoiseData is READ_WRITE variable, onNoiseDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onNoiseDataChange()  {
  // Read Noise sensor value
  int noise_Data = analogRead(noise_sensor);

  Serial.print("Light Analog Value = ");
  Serial.print(noise_Data);   // the raw analog reading

  /*// Determine light level based on analog value
    if (noise_Data < 400) {
    Serial.println(" => Fault");
    } else {
    Serial.println(" => Normal");
    }*/

  delay(500);
}

/*
  Since LightData is READ_WRITE variable, onLightDataChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightDataChange()  {
  // Read light sensor value
  int light_Data = analogRead(light_sensor);

  Serial.print("Light Analog Value = ");
  Serial.print(light_Data);   // the raw analog reading

  // Determine light level based on analog value
  if (light_Data < 400) {
    Serial.println(" => Fault");
  } else {
    Serial.println(" => Normal");
  }

  delay(500);
}
