// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ddb8f0e4-2fe5-4a52-8d33-3fc627b56d12";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGasDataChange();
void onLightDataChange();
void onNoiseDataChange();
void onTemperatureChange();

int gas_Data;
int light_Data;
int noise_Data;
int temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gas_Data, READWRITE, ON_CHANGE, onGasDataChange);
  ArduinoCloud.addProperty(light_Data, READWRITE, ON_CHANGE, onLightDataChange);
  ArduinoCloud.addProperty(noise_Data, READWRITE, ON_CHANGE, onNoiseDataChange);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
